staging:
  environment: "staging"
  account: "034362052544"
  app_name: "mentorship"
  region: "us-east-1"
  cognito_authorizer: "cognito-authorizer-staging"
  cognito_pool_arn: "arn:aws:cognito-idp:us-east-1:034362052544:userpool/us-east-1_jHuY6weHT"
  cognito_client_id: "685s5u6r6ntuti730g5foo20qq"
  user_profile_ddb_table_name: "user_profiles_staging"
  user_pool_name: "mentorship-pool-staging"
  bucket_name: "big-bucket-staging"
  slack_webhook_secret_arn: "arn:aws:secretsmanager:us-east-1:034362052544:secret:webhook_url/slack/notifier-xFQdTJ"
  endpoint_base_url: "https://wu706j7j2k.execute-api.us-east-1.amazonaws.com/staging"

production:
  environment: "production"
  account: "034362052544"
  app_name: "mentorship"
  region: "us-east-1"
  cognito_authorizer: "cognito-authorizer-production"
  cognito_pool_arn: "arn:aws:cognito-idp:us-east-1:034362052544:userpool/us-east-1_SF5ataedj"
  cognito_client_id: "3nuu7k13hgfdgej57nas4lmuft"
  user_profile_ddb_table_name: "user_profiles_production"
  user_pool_name: "mentorship-pool-production"
  bucket_name: "big-bucket-production"
  slack_webhook_secret_arn: "arn:aws:secretsmanager:us-east-1:034362052544:secret:webhook_url/slack/notifier-xFQdTJ"
  endpoint_base_url: "https://75aud4a07b.execute-api.us-east-1.amazonaws.com/production"