environment:
  staging: "staging"
  production: "production"
  app_name: "mentorship"
context:
  account: "034362052544"
  region: "us-east-1"
bucket_name: "big-bucket"
route_name: "api-routes"
cognito:
  staging_client_id: "685s5u6r6ntuti730g5foo20qq"
  production_client_id: "4bfqmpvbbq73eksgdtsvvuptve"