staging:
  environment: "staging"
  account: "034362052544"
  app_name: "mentorship"
  region: "us-east-1"
  cognito_pool_arn: "arn:aws:cognito-idp:us-east-1:034362052544:userpool/us-east-1_jHuY6weHT"
  cognito_client_id: "685s5u6r6ntuti730g5foo20qq"
  bucket_name: "big-bucket-staging"
  slack_webhook_secret_arn: "arn:aws:secretsmanager:us-east-1:034362052544:secret:webhook_url/slack/notifier-xFQdTJ"

production:
  environment: "production"
  account: "034362052544"
  app_name: "mentorship"
  region: "us-east-1"
  cognito_pool_arn: "arn:aws:cognito-idp:us-east-1:034362052544:userpool/us-east-1_SF5ataedj"
  cognito_client_id: "3nuu7k13hgfdgej57nas4lmuft"
  bucket_name: "big-bucket-production"
  slack_webhook_secret_arn: "arn:aws:secretsmanager:us-east-1:034362052544:secret:webhook_url/slack/notifier-xFQdTJ"
