name: CDK Build and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  cdk-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for CDK
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: go mod download

      - name: Build CDK app
        run: go build -o cdk.out/mentorship-app main.go

      - name: Synthesize CDK stack
        run: cdk synth
