name: CDK Deployments

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Choose environment (staging or production)'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker pull amazonlinux:2

      - name: Discover and Build Lambda Functions
        run: |
          for dir in $(find handlers/s3/* -type d); do
            if [ -f "$dir/main.go" ]; then
              function_name=$(basename "$dir")
              echo "Building Lambda function: $function_name"
              docker build -t $function_name-lambda -f "$dir/Dockerfile" "$dir"
              docker run --rm -v "$PWD/$dir":/app $function_name-lambda cp /app/function.zip /app/${function_name}_function.zip
            fi
          done
        shell: bash

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Synthesize the CDK stack
        run: cdk synth

      - name: Deploy Stack
        run: |
          if [ "${{ github.event.inputs.target_environment }}" == "staging" ]; then
            cdk deploy MentorshipAppBackendStagingStack --require-approval never
          elif [ "${{ github.event.inputs.target_environment }}" == "production" ]; then
            cdk deploy MentorshipAppBackendProductionStack --require-approval never
          fi
